//https://www.ala.org/advocacy/bbooks/frequentlychallengedbooks/YAbooks

function randomCover() {
  let books = [
    { img: "images/13reasonswhy.jpeg",
     text: "13 Reasons Why follows teenager Clay Jensen as he <br>returns home from school to find a mysterious box <br>with his name on it lying on his porch. <br>Inside he  discovers cassette tapes recorded by Hannah Baker—his <br>classmate and crush—who tragically committed suicide two weeks earlier."
    },
    { img: "images/genderqueer.jpeg",
     text:"A memoir that tells a story of a person growing <br>up questioning both their sexuality and gender",
    },
    { img: "images/1984.jpeg",
     text:"Nineteen Eighty-Four is a dystopian social science fiction <br>novel and cautionary tale written by English writer George Orwell",
    },
    { img: "images/451.jpeg",
     text:"Fahrenheit 451 is a 1953 dystopian novel by American writer <br>Ray Bradbury. Often regarded as one of his best works, <br>the novel presents a future American society where books are <br>outlawed and 'firemen' burn any that are found",
    },
    { img: "images/allamericanboys.jpeg",
     text:"The book tells the story of two teenage boys, <br>Rashad Butler and Quinn Collins, as they handle racism and police brutality in their community.",
    },
    { img: "images/1619.jpeg",
     text:"The 1619 Project was launched in August 2019 to <br>commemorate the 400th anniversary of the arrival of the <br>first enslaved Africans in colonial Virginia. In 1619, a <br>group of 'twenty and odd' captive Africans arrived in <br>the Virginia Colony.",
    },
    { img: "images/allboysarentblue.jpeg",
     text:"All Boys Aren't Blue is a young adult non-fiction <br>'memoir-manifesto' by journalist and activist George M. Johnson,<br> published April 28, 2020, by Farrar, Straus and Giroux. The <br>book consists of a series of essays following Johnson's journey <br>growing up as a queer Black man in<br> Plainfield, New Jersey, and Virginia.",
    },
    { img: "images/ants.jpeg",
     text:"A novel about a teenage boy who must decide whether <br>or not the world is worth saving. Henry Denton has <br>spent years being periodically abducted by aliens. Then the aliens <br>give him an ultimatum: The world will end in 144 days, <br>and all Henry has to do to stop it is push a <br>big red button. Only he isn’t sure he wants to. <br>After all, life hasn’t been great for Henry.",
    },
    { img: "images/annefrank.jpeg",
     text:"It tells the story of her family who live in <br>Frankfurt, Germany and suddenly have to go into hiding as <br>a result of Hitler and the Nazi Party's treatment of <br>Jews in Europe during the second world war. They escape <br>to Amsterdam where they go into hiding with other Jews.",
    },
    { img: "images/animalfarm.jpeg",
     text:"The book tells the story of a group of farm animals<br> who rebel against their human farmer, hoping to create a<br> society where the animals can be equal, free, and happy. <br>Ultimately, the rebellion is betrayed, and the farm ends up in <br>a state as bad as it was before, under the <br>dictatorship of a pig named Napoleon.",
    },
    { img: "images/anger.jpeg",
     text:"Six years ago, Moss Jefferies' father was murdered by an <br>Oakland police officer. Along with losing a parent, the media' s <br>vilification of his father and lack of accountability has left <br>Moss with near crippling panic attacks. Now, in his sophomore <br>year of high school, Moss and his fellow classmates find<br> themselves increasingly treated like criminals their own school. New rules. <br>Random locker searches. Constant intimidation and Oakland Police Department <br>stationed in their halls. Despite their youth, the students decide <br>to organize and push back against the administration.",
    },
    { img: "images/beartown.jpeg",
     text:"The story follows the events leading up to the rape <br>of 15-year-old girl Maya Andersson by the star <br>junior hockey player Kevin Erdahl, and the consequences for Maya <br>and Kevin, the players, their families, friends, and the community <br>which has a long-standing reputation as a hockey town.",
    },
    { img: "images/fault.jpg",
     text:"A young teenage girl who has been diagnosed with lung <br>cancer and attends a cancer support group. Hazel is 16 <br>and is reluctant to go to the support group, but she <br>soon realises that it was a good idea. Hazel meets <br>a young boy named Augustus Waters.",
    },
    { img: "images/indian.jpeg",
     text:"Junior, a budding cartoonist growing up on the Spokane Indian <br>Reservation. Determined to take his future into his own hands, <br>Junior leaves his troubled school on the rez to attend <br>an all-white farm town high school where the only <br>other Indian is the school mascot.",
    },
    { img: "images/perk.jpg",
     text:"Perks follows observant 'wallflower' Charlie as he charts a course <br>through the strange world between adolescence and adulthood. First <br>dates, family drama, and new friends. Sex, drugs, and The Rocky <br>Horror Picture Show. Devastating loss, young love, and life on <br>the fringes. Caught between trying to live his life and <br>trying to run from it, Charlie must learn to navigate <br>those wild and poignant roller-coaster days known as growing up.",
    },
    { img: "images/fat.jpg",
     text:"Sarah Byrnes and Eric Calhoune have been friends for years. <br>When they were children, his weight and her scars made <br>them both outcasts. Now Sarah Byrnes—the smartest, toughest person <br>Eric has ever known—sits silent in a hospital. Eric <br>must uncover the terrible secret she’s hiding before its dark <br>current pulls them both under.",
    },
    { img: "images/post.jpg",
     text:"When Cameron Post’s parents die suddenly in a car crash, her <br>shocking first thought is relief. Relief they’ll never know that, <br>hours earlier, she had been kissing a girl. But that <br>relief doesn’t last, and Cam is forced to move in with <br>her conservative aunt Ruth and her well-intentioned but <br>hopelessly old-fashioned grandmother. She knows that from this point <br>on, her life will forever be different. Survival in Miles City, <br>Montana, means blending in and leaving well enough alone, and <br>Cam becomes an expert at both.",
    },
    { img: "images/eve.jpeg",
     text:"The girls at Modesta High School feel like they're stuck <br>in some anti-feminist time warp-they're faced with sexism <br>at every turn, and they've had enough. Sponsored by their <br>new art teacher, Ms. Stark, they band together to form <br>the Daughters of Eve. It's more than a school club-it's <br>a secret society, a sisterhood. ",
    },
    { img: "images/neverwhere.jpeg",
     text:"Richard Mayhew is an unassuming young businessman living in London, <br>with a dull job and a pretty but demanding fiancee. Then one <br>night he stumbles across a girl bleeding on the sidewalk. He <br>stops to help her--and the life he knows vanishes like smoke. <br>Several hours later, the girl is gone too. And by the <br>following morning Richard Mayhew has been erased from his world. <br>His bank cards no longer work, taxi drivers won't stop for him, <br>his landlord rents his apartment out to strangers. He has become <br>invisible, and inexplicably consigned to a London of shadows and darkness a <br>city of monsters and saints, murderers and angels, that exists <br>entirely in a subterranean labyrinth of sewer canals and abandoned subway <br>stations. He has fallen through the cracks of reality and <br>has landed somewhere different, somewhere that is Neverwhere.",
    },
    { img: "images/carrie.jpg",
     text:"An unpopular teenage girl whose mother is a religious fanatic <br>is tormented and teased to the breaking point by her <br>more popular schoolmates and uses her hidden telekinetic<br> powers to inflict a terrifying revenge.",
    },
    { img: "images/chocolate.jpeg",
     text:"Vivian Gandillon relishes the change, the sweet, fierce ache <br>that carries her from girl to wolf. At sixteen, <br>she is beautiful and strong, and all the young <br>wolves are on her tail. But Vivian still grieves <br>for her dead father; her pack remains leaderless and <br>in disarray, and she feels lost in the suburbs <br>of Maryland. She longs for a normal life. But what<br> is normal for a werewolf?",
    },
    { img: "images/dead.jpg",
     text:"When Alice was ten, Ray took her away from her family, <br>her friends -- her life. She learned to give up all power,<br> to endure all pain. She waited for the nightmare to be over.",
    },
    { img: "images/prep.jpeg",
     text:"Lee Fiora is an intelligent, observant fourteen-year-old when her <br>father drops her off in front of her dorm at the prestigious<br> Ault School in Massachusetts. She leaves her animated, affectionate <br>family in South Bend, Indiana, at least in part because of <br>the boarding school’s glossy brochure, in which boys in sweaters <br>chat in front of old brick buildings, girls in kilts hold<br> lacrosse sticks on pristinely mown athletic fields, and everyone sings <br>hymns in chapel.",
    },
    { img: "images/handmaid.jpeg",
     text:"The Handmaid's Tale is the story of life in the <br>dystopia of Gilead, a totalitarian society in what was the <br>United States. Gilead is ruled by a fundamentalist regime that <br>treats women as property of the state, and is faced <br>with environmental disasters and a plummeting birth rate.",
    },
    { img: "images/blue.jpeg",
     text:"Each of these stories is original, each is by a noted <br>author for young adults, and each honestly portrays its subject and <br>theme--growing up gay or lesbian, or with gay or <br>lesbian parents or friends",
    },
    { img: "images/thieves.jpeg",
     text:"During the Nazis’ brutal siege of Leningrad, Lev Beniov is arrested <br>for looting and thrown into the same cell as a handsome <br>deserter named Kolya. Instead of being executed, Lev and Kolya are <br>given a shot at saving their own lives by complying <br>with an outrageous directive: secure a dozen eggs for a <br>powerful Soviet colonel to use in his daughter’s wedding cake. <br>In a city cut off from all supplies and suffering unbelievable <br>deprivation, Lev and Kolya embark on a hunt through the <br>dire lawlessness of Leningrad and behind enemy lines to find the impossible.",
    },
    { img: "images/tortilla.jpeg",
     text:"Topanga Canyon is home to two couples on a collision course. <br>Los Angeles liberals Delaney and Kyra Mossbacher lead an ordered <br>sushi-and-recycling existence in a newly gated hilltop community: <br>he a sensitive nature writer, she an obsessive realtor. Mexican illegals <br>Cándido and América Rincón desperately cling to their vision of the <br>American Dream as they fight off starvation in a makeshift camp <br>deep in the ravine. And from the moment a freak accident <br>brings Cándido and Delaney into intimate contact, these four and their <br>opposing worlds gradually intersect in what becomes a tragicomedy of <br>error and misunderstanding.",
    },
    { img: "images/dance.jpeg",
     text:"In this revelatory, groundbreaking novel, the love of sixteen-year-old <br>Hal Robinson for self-confident Barry Gorman is revealed <br>through Hal’s own observations, press clippings, and the scattered <br>notes of a social worker. These various perspectives contribute <br>to an extraordinarily sensitive portrait of the intensity of <br>first love.",
    },
    { img: "images/capone.jpeg",
     text:"Today I moved to a twelve-acre rock covered with cement, <br>topped with bird turd and surrounded by water. I'm not the <br>only kid who lives here. There's my sister, Natalie, except <br>she doesn't count. And there are twenty-three other kids who <br>live on the island because their dads work as guards or <br>cook's or doctors or electricians for the prison, like my dad does. <br>Plus, there are a ton of murderers, rapists, hit men, <br>con men, stickup men, embezzlers, connivers, burglars, kidnappers and maybe even an<br> innocent man or two, though I doubt it. The convicts we <br>have are the kind other prisons don't want. I never knew <br>prisons could be picky, but I guess they can. You get <br>to Alcatraz by being the worst of the worst. Unless <br>you're me. I came here because my mother said I had to.",
    },
    { img:"images/super.jpeg",
     text:"In the future, in a place called Satelite City, <br>fourteen-year-old Cosmo Hill enters the world, <br>unwanted by his parents. He's sent to the Clarissa <br>Frayne Institute for Parentally Challenged Boys, Freight class. At <br>Clarissa Frayne, the boys are put to work by the <br>state, testing highly dangerous products. At the end of <br>most days, they are covered with burns, bruises, and <br>sores. Cosmo realizes that if he doesn't escape, he <br>will die at this so-called orphanage."},
    { img:"images/happens.jpeg",
     text :"At the start of her senior year in high school, <br>Sara wants two things: to get into a top college and <br>to find true love. Tobey also wants two things for his <br>senior year: to win Battle of the Bands and to <br>make Sara fall in love with him. However, a popular jock <br>named Dave moves in on Sara first. But Tobey's <br>quirky wit and big blue eyes are hard for Sara to <br>ignore. Plus, he gets the little things that matter to her. <br>Can a slacker rock-star wannabe win the heart of <br>a pretty class brain like Sara?"},
    { img:"images/hunger.jpeg",
     text :"In the ruins of a place once known as North America <br>lies the nation of Panem, a shining Capitol surrounded by<br> twelve outlying districts. The Capitol is harsh and cruel <br>and keeps the districts in line by forcing them <br>all to send one boy and one girl between <br>the ages of twelve and eighteen to participate in <br>the annual Hunger Games, a fight to the death <br>on live TV."},
    { img:"images/outsiders.jpeg",
     text :"The Outsiders is about two weeks in the life <br>of a 14-year-old boy. The novel tells <br>the story of Ponyboy Curtis and his struggles with <br>right and wrong in a society in which he believes that he is an outsider."},
    { img:"images/dancing.jpeg",
     text :"Samantha and Juliana. Sam and Jules -- they've been <br>best friends forever. Now, in the summer before their <br>senior year, they're ready for whatevers coming. College? Professional <br>dance careers? They'll share the triumphs and face the <br>tears together. But neither of them are prepared for <br>what does happen next. Jules is diagnosed with cancer. <br>And there is no cure. "},
    { img:"images/triangle.jpeg",
     text :"'Their friendship went so far back, it bordered on <br>the Biblical -- in the beginning, there was Nina <br>and Avery and Mel.' So says high school <br>senior Nina Bermudez about herself and her two best <br>friends, nicknamed 'The Bermudez Triangle' by a jealous wannabe <br>back on Nina's eleventh birthday. But the threesome faces <br>their first separation when Nina goes away the summer <br>before their senior year. And in ten short weeks, <br>everything changes."},
    { img:"images/vampire.jpeg",
     text :"Lissa Dragomir is a Moroi princess: a mortal vampire <br>with a rare gift for harnessing the earth's magic. <br>She must be protected at all times from Strigoi; <br>the fiercest vampires—the ones who never die. The <br>powerful blend of human and vampire blood that flows <br>through Rose Hathaway, Lissa's best friend, makes her a dhampir.<br> Rose is dedicated to a dangerous life of protecting <br>Lissa from the Strigoi, who are hell-bent on <br>making Lissa one of them."},
    { img:"images/killers.jpeg",
     text :"Jasper 'Jazz' Dent is a likable teenager. A charmer,<br> one might say. But he's also the son of <br>the world's most infamous serial killer, and for <br>Dear Old Dad, Take Your Son to Work Day <br>was year-round. Jazz has witnessed crime scenes the <br>way cops wish they could—from the criminal's <br>point of view."},
    // { img:"",
    //  text :""},
    // { img:"",
    //  text :""},
    // { img:"",
    //  text :""},
    // { img:"",
    //  text :""},
    // { img:"",
    //  text :""},
      
  ];

  let book = books[Math.floor(Math.random()*books.length)];

  document.getElementById("demo").innerHTML =         
  '<p>' + book.text + '</p>' +
        '<img src="' + book.img + '">';
  
}

